// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASmBCWSp-AB0pj1BzPV3cIs4M0NjMRP4',
    appId: '1:186588725768:web:4bb433c74d10b00b50c7bd',
    messagingSenderId: '186588725768',
    projectId: 'push-notification-b21a0',
    authDomain: 'push-notification-b21a0.firebaseapp.com',
    storageBucket: 'push-notification-b21a0.appspot.com',
    measurementId: 'G-XPT3ZGYTK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuwJtP8gLBnWNuA7czarhhaRUvlw80g5g',
    appId: '1:186588725768:android:b4db167228e9e3b850c7bd',
    messagingSenderId: '186588725768',
    projectId: 'push-notification-b21a0',
    storageBucket: 'push-notification-b21a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Z8M_sIrHtJ2mEs9leNhyQY1hRmJUa-U',
    appId: '1:186588725768:ios:3993f8c6fc97c10750c7bd',
    messagingSenderId: '186588725768',
    projectId: 'push-notification-b21a0',
    storageBucket: 'push-notification-b21a0.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Z8M_sIrHtJ2mEs9leNhyQY1hRmJUa-U',
    appId: '1:186588725768:ios:370feb6a2a0d86df50c7bd',
    messagingSenderId: '186588725768',
    projectId: 'push-notification-b21a0',
    storageBucket: 'push-notification-b21a0.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
